// src/js/ipc/channels.js

'use strict';

const CHANNELS = Object.freeze({
  CHECK_FILE_EXISTS: 'check-file-exists',
  CLEAR_HISTORY: 'clear-history',
  DELETE_FILE: 'delete-file',
  DOWNLOAD_UPDATE: 'download-update',
  DOWNLOAD_VIDEO: 'download-video',
  GET_AUTO_LAUNCH_STATUS: 'get-auto-launch-status',
  GET_AUTO_SHUTDOWN_DEADLINE: 'get-auto-shutdown-deadline',
  GET_AUTO_SHUTDOWN_SECONDS: 'get-auto-shutdown-seconds',
  GET_AUTO_SHUTDOWN_STATUS: 'get-auto-shutdown-status',
  GET_CLOSE_NOTIFICATION_STATUS: 'get-close-notification-status',
  GET_DEFAULT_TAB: 'get-default-tab',
  GET_DISABLE_COMPLETE_MODAL_STATUS: 'get-disable-complete-modal-status',
  GET_DISABLE_GLOBAL_SHORTCUTS_STATUS: 'get-disable-global-shortcuts-status',
  GET_DOWNLOAD_COUNT: 'get-download-count',
  GET_DOWNLOAD_PATH: 'get-download-path',
  GET_FILE_SIZE: 'get-file-size',
  GET_FONT_SIZE: 'get-font-size',
  GET_ICON_PATH: 'get-icon-path',
  GET_MINIMIZE_INSTEAD_OF_CLOSE_STATUS: 'get-minimize-instead-of-close-status',
  GET_MINIMIZE_ON_LAUNCH_STATUS: 'get-minimize-on-launch-status',
  GET_MINIMIZE_TO_TRAY_STATUS: 'get-minimize-to-tray-status',
  GET_OPEN_ON_COPY_URL_STATUS: 'get-open-on-copy-url-status',
  GET_OPEN_ON_DOWNLOAD_COMPLETE_STATUS: 'get-open-on-download-complete-status',
  GET_PLATFORM_INFO: 'get-platform-info',
  GET_THEME: 'get-theme',
  GET_VERSION: 'get-version',
  GET_WHATS_NEW: 'get-whats-new',
  LOAD_HISTORY: 'load-history',
  OPEN_CONFIG_FOLDER: 'open-config-folder',
  OPEN_DOWNLOAD_FOLDER: 'open-download-folder',
  OPEN_EXTERNAL_LINK: 'open-external-link',
  OPEN_LAST_VIDEO: 'open-last-video',
  OPEN_TERMINAL: 'open-terminal',
  RESTART_APP: 'restart-app',
  SAVE_HISTORY: 'save-history',
  SELECT_DOWNLOAD_FOLDER: 'select-download-folder',
  SET_AUTO_SHUTDOWN_SECONDS: 'set-auto-shutdown-seconds',
  SET_AUTO_SHUTDOWN_STATUS: 'set-auto-shutdown-status',
  SET_CLOSE_NOTIFICATION_STATUS: 'set-close-notification-status',
  SET_DEFAULT_TAB: 'set-default-tab',
  SET_DISABLE_COMPLETE_MODAL_STATUS: 'set-disable-complete-modal-status',
  SET_DISABLE_GLOBAL_SHORTCUTS_STATUS: 'set-disable-global-shortcuts-status',
  SET_DOWNLOAD_PATH: 'set-download-path',
  SET_FONT_SIZE: 'set-font-size',
  SET_MINIMIZE_INSTEAD_OF_CLOSE: 'set-minimize-instead-of-close',
  SET_MINIMIZE_ON_LAUNCH_STATUS: 'set-minimize-on-launch-status',
  SET_MINIMIZE_TO_TRAY_STATUS: 'set-minimize-to-tray-status',
  SET_OPEN_ON_COPY_URL_STATUS: 'set-open-on-copy-url-status',
  SET_OPEN_ON_DOWNLOAD_COMPLETE_STATUS: 'set-open-on-download-complete-status',
  SET_THEME: 'set-theme',
  SHOW_SYSTEM_NOTIFICATION: 'show-system-notification',
  STOP_DOWNLOAD: 'stop-download',
  TOAST: 'toast',
  TOGGLE_AUTO_LAUNCH: 'toggle-auto-launch',
  TOOLS_CHECKUPDATES: 'tools:checkUpdates',
  TOOLS_GETVERSIONS: 'tools:getVersions',
  TOOLS_INSTALLALL: 'tools:installAll',
  TOOLS_SHOWINFOLDER: 'tools:showInFolder',
  TOOLS_UPDATEFFMPEG: 'tools:updateFfmpeg',
  TOOLS_UPDATEYTDLP: 'tools:updateYtDlp',
  WG_OPEN_CONFIG_FOLDER: 'wg-open-config-folder',
});

const CHANNELS_LIST = Object.freeze(Object.values(CHANNELS));

module.exports = { CHANNELS, CHANNELS_LIST };